# This is a basic workflow to help you get started with Actions

name: apigee-deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  apigee_deployment_job:
    runs-on: ubuntu-latest
    name: Deploy Apigee Proxy
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    #- name: Retrieve variables from .env
    #  id: dotenv
    #  uses: falti/dotenv-action@v0.2.4

    #- name: Display variables
    #  run: |
    #    echo "org: " $APIGEE_ORGANIZATION
    #    echo "env: " $APIGEE_ENV
    #    set
    #    pwd
    
   # - name: Deployment
    #  id: deployment
   #   uses: g-lalevee/apigeetool-deployment-action@v1.0
   #  with:
    #    APIGEE_USERNAME: ${{ secrets.APIGEE_ID }}
    #    APIGEE_PASSWORD: ${{ secrets.APIGEE_PWD }}  
    #    APIGEETOOL_ERROR_STOP: false
          
    # Use the output from the `Deployment` step
    #- name: Get the Apigeetool Return Code
    #  run: echo "Apigeetool ended with code ${{ steps.deployment.outputs.RC }}"

    - uses: matt-ball/newman-action@master
      with:
        collection: petstore.postman_collection.jsodn
        environment: .env
        iterationCount: 2


